return {
  "LazyVim/LazyVim",
  version = false,
  opts = {
    -- colorscheme = "tokyonight",
    colorscheme = "nightfox",

    icons = {
      misc = {
        dots = "󰇘",
      },
      dap = {
        Stopped = { "󰁕", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint = { "", "DiagnosticError" },
        BreakpointCondition = { "", "DiagnosticError" },
        BreakpointRejected = { "", "DiagnosticError" },
        LogPoint = "",
      },
      diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = "󰌵 ",
        Info = " ",
      },
      git = {
        added = " ",
        modified = " ",
        removed = " ",
      },
      kinds = {
        Codeium = "󰘦 ",
        Control = " ",
        Collapsed = " ",
        Copilot = " ",
        TabNine = "󰏚 ",

        Array = " ",
        Boolean = " ",
        Class = " ",
        Color = " ",
        Constant = " ",
        Constructor = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = "󰉋 ",
        Function = " ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Namespace = " ",
        Null = "󰟢 ",
        Number = " ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = " ",
      },
    },
  },
}
